### ISSUE TITLE
활성화가 안 됩니다.

### ISSUE THREAD

**Issue by linuking** [akasima/xero_commerce#105]
xe3 및 xero_commerce를 여러번 재설치 하고 해 봐도 항상 같은 곳에서 에러가 발생하고 활성화에 실패합니다.
바쁘시겠지만, 아래 laravel-2019-12-29.log 에러 메세지 확인하시고 조언 바랍니다.

####
참고  :  다른 플러그인은 활성화, 비활성화가 에러없이 잘 이루어지고 있습니다.  다만, xero_commece 플러그인만 아래와 같이 에러가 나더라구요. 
#### 

laravel-2019-12-29.log 에러 메세지 

production.ERROR: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'xe_xero_commerce_user' already exists (SQL: create table `xe_xero_commerce_user` (`id` int unsigned not null auto_increment primary key, `user_id` varchar(36) not null, `name` varchar(255) not null, `phone` varchar(255) not null, `level` int not null) default character set utf8mb4 collate utf8mb4_unicode_ci) {"userId":"3b1ab72a-7fa2-4ee7-bb74-48d096a014d7","email":"king@aaaking.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'xe_xero_commerce_user' already exists (SQL: create table `xe_xero_commerce_user` (`id` int unsigned not null auto_increment primary key, `user_id` varchar(36) not null, `name` varchar(255) not null, `phone` varchar(255) not null, `level` int not null) default character set utf8mb4 collate utf8mb4_unicode_ci) at /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'xe_xero_commerce_user' already exists at /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458)
[stacktrace]
#0 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('create table `x...', Array, Object(Closure))
#1 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('create table `x...', Array, Object(Closure))
#2 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(86): Illuminate\\Database\\Connection->statement('create table `x...')
#3 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(252): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#4 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(165): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#5 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Database\\Schema\\Builder->create('xero_commerce_u...', Object(Closure))
#6 /gome/oppud/xe3/plugins/xero_commerce/src/Plugin/Database.php(29): Illuminate\\Support\\Facades\\Facade::__callStatic('create', Array)
#7 /gome/oppud/xe3/plugins/xero_commerce/plugin.php(79): Xpressengine\\Plugins\\XeroCommerce\\Plugin\\Database::create()
#8 [internal function]: Xpressengine\\Plugins\\XeroCommerce\\Plugin->install()
#9 /gome/oppud/xe3/core/src/Xpressengine/Plugin/PluginEntity.php(709): call_user_func_array(Array, Array)
#10 /gome/oppud/xe3/core/src/Xpressengine/Plugin/PluginHandler.php(372): Xpressengine\\Plugin\\PluginEntity->__call('install', Array)
#11 [internal function]: Xpressengine\\Plugin\\PluginHandler->updatePlugin('xero_commerce', false)
#12 /gome/oppud/xe3/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(108): call_user_func_array('parent::updateP...', Array)
#13 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->_proxyTargetCall('updatePlugin', Array)
#14 /gome/oppud/xe3/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(92): call_user_func_array(Array, Array)
#15 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->Xpressengine\\Interception\\Proxy\\{closure}('xero_commerce', false)
#16 /gome/oppud/xe3/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(96): call_user_func_array(Object(Closure), Array)
#17 [internal function]: Xpressengine\\Interception\\ProxyInvocationHandler->__invoke('xero_commerce', false)
#18 /gome/oppud/xe3/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(74): call_user_func_array(Object(Xpressengine\\Interception\\ProxyInvocationHandler), Array)
#19 /gome/oppud/xe3/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(94): Xpressengine\\Interception\\ProxyInvocationHandler->callProxy(Array, Object(Closure))
#20 /gome/oppud/xe3/storage/app/interception/Proxy_Xpressengine_Plugin_PluginHandler.php(55): Proxy_Xpressengine_Plugin_PluginHandler->_proxyMethodCall('updatePlugin', Array)
#21 /gome/oppud/xe3/core/src/Xpressengine/Plugin/PluginHandler.php(255): Proxy_Xpressengine_Plugin_PluginHandler->updatePlugin('xero_commerce', false)
#22 [internal function]: Xpressengine\\Plugin\\PluginHandler->activatePlugin('xero_commerce')
#23 /gome/oppud/xe3/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(108): call_user_func_array('parent::activat...', Array)
#24 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->_proxyTargetCall('activatePlugin', Array)
#25 /gome/oppud/xe3/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(92): call_user_func_array(Array, Array)
#26 [internal function]: Proxy_Xpressengine_Plugin_PluginHandler->Xpressengine\\Interception\\Proxy\\{closure}('xero_commerce')
#27 /gome/oppud/xe3/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(96): call_user_func_array(Object(Closure), Array)
#28 [internal function]: Xpressengine\\Interception\\ProxyInvocationHandler->__invoke('xero_commerce')
#29 /gome/oppud/xe3/core/src/Xpressengine/Interception/ProxyInvocationHandler.php(74): call_user_func_array(Object(Xpressengine\\Interception\\ProxyInvocationHandler), Array)
#30 /gome/oppud/xe3/core/src/Xpressengine/Interception/Proxy/ProxyTrait.php(94): Xpressengine\\Interception\\ProxyInvocationHandler->callProxy(Array, Object(Closure))
#31 /gome/oppud/xe3/storage/app/interception/Proxy_Xpressengine_Plugin_PluginHandler.php(40): Proxy_Xpressengine_Plugin_PluginHandler->_proxyMethodCall('activatePlugin', Array)
#32 /gome/oppud/xe3/app/Http/Controllers/Plugin/PluginManageController.php(155): Proxy_Xpressengine_Plugin_PluginHandler->activatePlugin('xero_commerce')
#33 [internal function]: App\\Http\\Controllers\\Plugin\\PluginManageController->activate(Object(Xpressengine\\Http\\Request), Object(Proxy_Xpressengine_Plugin_PluginHandler), Object(Xpressengine\\Interception\\InterceptionHandler))
#34 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#35 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('activate', Array)
#36 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Plugin\\PluginManageController), 'activate')
#37 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#38 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#39 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#40 /gome/oppud/xe3/core/src/Xpressengine/Settings/SettingsMiddleware.php(89): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#41 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Xpressengine\\Settings\\SettingsMiddleware->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#42 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#43 /gome/oppud/xe3/app/Http/Middleware/AsyncExpose.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#44 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\AsyncExpose->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#45 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#46 /gome/oppud/xe3/app/Http/Middleware/FreezeSEO.php(42): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#47 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\FreezeSEO->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#48 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#49 /gome/oppud/xe3/app/Http/Middleware/Purifying.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#50 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Purifying->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#51 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#52 /gome/oppud/xe3/app/Http/Middleware/LangPreprocessor.php(87): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#53 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LangPreprocessor->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#54 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#55 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#56 /gome/oppud/xe3/app/Http/Middleware/ExceptAppendableVerifyCsrfToken.php(49): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#57 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ExceptAppendableVerifyCsrfToken->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#58 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#59 /gome/oppud/xe3/app/Http/Middleware/RequiredDF.php(71): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#60 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\RequiredDF->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#61 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#62 /gome/oppud/xe3/app/Http/Middleware/HttpProtocol.php(44): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#63 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpProtocol->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#64 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#65 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#66 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#67 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#68 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#69 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#70 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#71 /gome/oppud/xe3/app/Http/Middleware/ShareLocalizeSession.php(69): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#72 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ShareLocalizeSession->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#73 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#74 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#75 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#76 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#77 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#78 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#79 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#80 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#81 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#82 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#83 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#84 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#85 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Xpressengine\\Http\\Request))
#86 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Xpressengine\\Http\\Request), Object(Illuminate\\Routing\\Route))
#87 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Xpressengine\\Http\\Request))
#88 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Xpressengine\\Http\\Request))
#89 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Xpressengine\\Http\\Request))
#90 /gome/oppud/xe3/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#91 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#92 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#93 /gome/oppud/xe3/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#94 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#95 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#96 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#97 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#98 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#99 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#100 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#101 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#102 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#103 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#104 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#105 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#106 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Xpressengine\\Http\\Request), Object(Closure))
#107 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Xpressengine\\Http\\Request))
#108 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#109 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#110 /gome/oppud/xe3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Xpressengine\\Http\\Request))
#111 /gome/oppud/xe3/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Xpressengine\\Http\\Request))
#112 {main}
"}

**Comment by Kazto-lsk** [comment]
DB에서 ```xe_xero_commerce``` 가 포함된 테이블을 모두 삭제 후 재시도해주시면 됩니다.
만약 이렇게 진행후 나오는 에러가 있을 경우 그 에러를 이미지로 알려주세요.

해결 방법이 있다면 알려드리겠습니다.
감사합니다.

**Comment by linuking** [comment]
위의 에러 내용은 말씀하신바와 같이 "xe_xero_" 관련 테이블을 모두 삭제하고 시도한 후 여전히 같은 에러 발생한 것입니다.
아래 이미지 파일 올립니다.

![1](https://user-images.githubusercontent.com/19444926/71575344-eeea2100-2b2f-11ea-8a5b-c1a81a76b2fb.jpg)

**Comment by Kazto-lsk** [comment]
#106 이슈를 이어 작성합니다.

아직 여전히 DB에서 xe_xero 로 시작하는 테이블이 삭제되지 않은 것 같습니다.
모두 xe_xero 로 시작하는 테이블을 삭제하면 그 다음에 있는 에러가 나올텐데요. 그 에러를 확인해야 할 것 같습니다.

어렵다면, 아예 초기화를 하는것도 방법이겠습니다.

**Comment by linuking** [comment]
여러번 삭제하고 재 새도한 결과의 메시지입니다.  물론 초기화 하고 xe3를 재설치 하고 여러번 시도해 봐도 같은 결과입니다.  ㅠㅠ

**Comment by Kazto-lsk** [comment]
답변이 늦었습니다.

에러가 동일하게 해당 에러가 나오고 있나요? 초기 XE설치 이후 DB도 모두 초기화 한 것이라면 나오지 않는것이 정상입니다.
